columns:
- name
- ra
- dec
- seq
- priority
- sciprog
- tag
- cycle
- ph_mk
- ph_start
- ph_end
- sunset_dt
- sunrise_dt
- h_min
- h_max
- fwhm_min
- fwhm_max
- uobi
- status
- pi
- P
- hjd0
- min_moon_dist
- max_moon_phase
- comment
- ob_time
- obs_data
- makro
- other
last_nights_to_mark: 10
tel:
  iris: null
  jk15: null
  test: null
  wk06: null
  zb08: null
